version: '3.2'
services:

  nginx:
    image: akiel/sample-locator-nginx:1
    ports:
    - ${PORT_NGINX:-8080}:80
    networks:
    - gba
    restart: always

  searchbroker-ui:
    image: martinbreu/searchbroker-ui:0
    environment:
      SEARCHBROKER_URL: ${SEARCHBROKER_UI_SEARCHBROKER_URL:-}
      NEGOTIATOR_URL: ${SEARCHBROKER_UI_NEGOTIATOR_URL:-}
      AUTH_CLIENT_SECRET: ${SEARCHBROKER_UI_AUTH_CLIENT_SECRET:-}
      AUTH_HOST: ${SEARCHBROKER_UI_AUTH_HOST:-}
      AUTH_PUBLIC_KEY: ${SEARCHBROKER_UI_AUTH_PUBLIC_KEY:-}
      AUTH_CLIENT_ID: ${SEARCHBROKER_UI_AUTH_CLIENT_ID:-}
      PROXY_HOST: ${SEARCHBROKER_UI_PROXY_HOST:-}
      PROXY_PORT: ${SEARCHBROKER_UI_PROXY_PORT:-}
      MDR_API_URL: ${SEARCHBROKER_UI_MDR_API_URL:-https://mdr.germanbiobanknode.de/v3/api/mdr}
      MDR_NAMESPACE: ${SEARCHBROKER_UI_MDR_NAMESPACE:-mdr16}
      MDR_LANGUAGE: ${SEARCHBROKER_UI_MDR_LANGUAGE:-en}
      MDR_MAPPING: ${SEARCHBROKER_UI_MDR_MAPPING:-<dataElementGroup nameOfEnum='DONOR'>urn:mdr16:dataelementgroup:5:1</dataElementGroup><dataElementGroup nameOfEnum='SAMPLE_CONTEXT'>urn:mdr16:dataelementgroup:4:1</dataElementGroup><dataElementGroup nameOfEnum='SAMPLE'>urn:mdr16:dataelementgroup:3:1</dataElementGroup><dataElementGroup nameOfEnum='EVENT'>urn:mdr16:dataelementgroup:6:1</dataElementGroup>}
      MDR_HIDDEN: ${SEARCHBROKER_UI_MDR_HIDDEN:-<hiddenDataElement>urn:mdr16:dataelement:1:1</hiddenDataElement><hiddenDataElement>urn:mdr16:dataelement:25:1</hiddenDataElement><hiddenDataElement>urn:mdr16:dataelement:34:1</hiddenDataElement><hiddenDataElement>urn:mdr16:dataelement:18:1</hiddenDataElement><hiddenDataElement>urn:mdr16:dataelement:11:1</hiddenDataElement><hiddenDataElement>urn:mdr16:dataelement:19:1</hiddenDataElement><hiddenDataElement>urn:mdr16:dataelement:20:1</hiddenDataElement><hiddenDataElement>urn:mdr16:dataelement:4:1</hiddenDataElement><hiddenDataElement>urn:mdr16:dataelement:21:1</hiddenDataElement><hiddenDataElement>urn:mdr16:dataelement:22:1</hiddenDataElement><hiddenDataElement>urn:mdr16:dataelement:24:1</hiddenDataElement><hiddenDataElement>urn:mdr16:dataelement:13:1</hiddenDataElement>}
      CATALINA_OPTS: ${SEARCHBROKER_UI_CATALINA_OPTS:--Xmx1g}
    networks:
    - gba
    restart: always

  searchbroker:
    image: martinbreu/searchbroker:1
    environment:
      AUTH_HOST: ${SEARCHBROKER_AUTH_HOST:-}
      AUTH_PUBLIC_KEY: ${SEARCHBROKER_AUTH_PUBLIC_KEY:-}
      AUTH_CLIENT_ID: ${SEARCHBROKER_AUTH_CLIENT_ID:-}
      MAIL_HOST: ${SEARCHBROKER_MAIL_HOST:-}
      MAIL_PORT: ${SEARCHBROKER_MAIL_PORT:-}
      MAIL_PROTOCOL: ${SEARCHBROKER_MAIL_PROTOCOL:-}
      MAIL_FROM_ADDRESS: ${SEARCHBROKER_MAIL_FROM_ADDRESS:-}
      MAIL_FROM_NAME: ${SEARCHBROKER_MAIL_FROM_NAME:-}
      POSTGRES_HOST: searchbroker-db
      POSTGRES_PORT: 5432
      POSTGRES_DB: searchbroker
      POSTGRES_USER: searchbroker
      POSTGRES_PASS: ${SEARCHBROKER_POSTGRES_PASS:-}
      PROXY_HOST: ${SEARCHBROKER_PROXY_HOST:-}
      PROXY_PORT: ${SEARCHBROKER_PROXY_PORT:-}
      CATALINA_OPTS: ${SEARCHBROKER_CATALINA_OPTS:-}
    networks:
    - gba
    - searchbroker-db
    depends_on:
    - searchbroker-db
    restart: always

  searchbroker-db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: searchbroker
      POSTGRES_PASSWORD: ${SEARCHBROKER_POSTGRES_PASS:-}
      POSTGRES_DB: searchbroker
    ports:
    - ${PORT_SEARCHBROKER_POSTGRES:-}:5432
    volumes:
    - type: volume
      source: searchbroker-db-data
      target: /var/lib/postgresql/data
    restart: always

networks:
  gba:
    driver: bridge
  searchbroker-db:
    driver: bridge

volumes:
  searchbroker-db-data:
