version: '3.4'
services:

  nginx:
    build: nginx
    ports:
      - "80:80"
    networks:
      - gba
    restart: always

  searchbroker-jsf-ui:
    image: martinbreu/searchbroker-ui:4.0.0
    environment:
      AUTH_CLIENT_ID:       ${AUTH_CLIENT_ID:-DUMMY}
      AUTH_CLIENT_SECRET:   ${AUTH_CLIENT_SECRET:-DUMMY}
      MOLGENIS_USERNAME:    "DUMMY"
      MOLGENIS_PASSWORD:    "DUMMY"
      SEARCHBROKER_URL:     "http://searchbroker:8080/broker"
      SAMPLELOCATOR_URL:    "https://samplelocator.bbmri.de"
      NEGOTIATOR_URL:       "https://negotiator.bbmri-eric.eu"
      AUTH_HOST:            "https://login.bbmri-eric.eu"
      AUTH_PUBLIC_KEY:      "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjKvsfThd4XO/J5PDlgnmCZ3vGB8MRwcK4rJ42xO/xVmtwkxV8ZW4LIbRE+uQn4EsyTY8ke9do2sSUHGSIHh6T0OR1nm9eljOEXwO6/kYPJbVvEYRIQaZ5kvuCZEP9dcyHwgaN9thHpo2n71GpVo+kZ/KhUY8XHU7PIUokCPIQrF20CvANa2h8htJMp3mIIBJ2j1sf7qfLo2QAJO5p92zASwPpZSebOFhqU5005Qp7uNB+Rv+1rwL2mclEcXRjmNQmStThOetZLgReoszE3obHyW65UprY269ulKAyqPVm653jtp5aYAt/sP1twgW9UY2+lkOMMpLYwZkTcg3eAW0vQIDAQAB"
      MDR_API_URL:          "https://mdr.test.bbmri.de/v3/api/mdr"
      MDR_NAMESPACE:        "mdr16"
      MDR_LANGUAGE:         "en"
      MDR_MAPPING:          '<dataElementGroup nameOfEnum="DONOR">urn:mdr16:dataelementgroup:5:1</dataElementGroup><dataElementGroup nameOfEnum="SAMPLE">urn:mdr16:dataelementgroup:3:1</dataElementGroup><dataElementGroup nameOfEnum="EVENT">urn:mdr16:dataelementgroup:6:1</dataElementGroup>'
      MDR_FIELD_PROPERTIES: '<dataElement><urn>urn:mdr16:dataelement:29:1</urn><placeHolder></placeHolder><unit>kg</unit></dataElement><dataElement><urn>urn:mdr16:dataelement:30:1</urn><placeHolder></placeHolder><unit>cm</unit></dataElement><dataElement><urn>urn:mdr16:dataelement:28:1</urn><placeHolder></placeHolder><unit>years</unit></dataElement><dataElement><urn>urn:mdr16:dataelement:14:1</urn><placeHolder></placeHolder><unit>years</unit></dataElement><dataElement><urn>urn:mdr16:dataelement:27:1</urn><placeHolder>e.g. C25.1</placeHolder><unit></unit></dataElement>'
      MDR_HIDDEN:           '<hiddenDataElement>urn:mdr16:dataelement:1:1</hiddenDataElement><hiddenDataElement>urn:mdr16:dataelement:25:1</hiddenDataElement><hiddenDataElement>urn:mdr16:dataelement:34:1</hiddenDataElement><hiddenDataElement>urn:mdr16:dataelement:18:1</hiddenDataElement><hiddenDataElement>urn:mdr16:dataelement:11:1</hiddenDataElement><hiddenDataElement>urn:mdr16:dataelement:19:1</hiddenDataElement><hiddenDataElement>urn:mdr16:dataelement:20:1</hiddenDataElement><hiddenDataElement>urn:mdr16:dataelement:4:1</hiddenDataElement><hiddenDataElement>urn:mdr16:dataelement:21:1</hiddenDataElement><hiddenDataElement>urn:mdr16:dataelement:22:1</hiddenDataElement><hiddenDataElement>urn:mdr16:dataelement:24:1</hiddenDataElement><hiddenDataElement>urn:mdr16:dataelement:13:1</hiddenDataElement>'
      CATALINA_OPTS:        '"-Xmx1g"'
    networks:
    - gba
    restart: always

  searchbroker-angular-ui:
    image: bjoernkroll/sample-locator:1.0.2
    environment:
      AUTH_CLIENT_ID:       ${AUTH_CLIENT_ID:-DUMMY}
      MOLGENIS_USERNAME:    "DUMMY"
      MOLGENIS_PASSWORD:    "DUMMY"
      SEARCHBROKER_URL:     "http://searchbroker:8080/broker"
      SAMPLELOCATOR_URL:    "https://samplelocator.bbmri.de"
      NEGOTIATOR_URL:       "https://negotiator.bbmri-eric.eu"
      AUTH_HOST:            "https://login.bbmri-eric.eu"
      AUTH_PUBLIC_KEY:      "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjKvsfThd4XO/J5PDlgnmCZ3vGB8MRwcK4rJ42xO/xVmtwkxV8ZW4LIbRE+uQn4EsyTY8ke9do2sSUHGSIHh6T0OR1nm9eljOEXwO6/kYPJbVvEYRIQaZ5kvuCZEP9dcyHwgaN9thHpo2n71GpVo+kZ/KhUY8XHU7PIUokCPIQrF20CvANa2h8htJMp3mIIBJ2j1sf7qfLo2QAJO5p92zASwPpZSebOFhqU5005Qp7uNB+Rv+1rwL2mclEcXRjmNQmStThOetZLgReoszE3obHyW65UprY269ulKAyqPVm653jtp5aYAt/sP1twgW9UY2+lkOMMpLYwZkTcg3eAW0vQIDAQAB"
      MDR_API_URL:          "https://mdr.test.bbmri.de/v3/api/mdr"
      MDR_NAMESPACE:        "mdr16"
      MDR_LANGUAGE:         "en"
      MDR_MAPPING:          '[{\"nameOfEnum\": \"DONOR\",\"urn\": \"urn:mdr16:dataelementgroup:5:1\"},{\"nameOfEnum\": \"SAMPLE\",\"urn\": \"urn:mdr16:dataelementgroup:3:1\"},{\"nameOfEnum\": \"EVENT\", \"urn\": \"urn:mdr16:dataelementgroup:6:1\"}]'
      MDR_FIELD_PROPERTIES: '[{\"urn\": \"urn:mdr16:dataelement:29:1\",\"placeholder\": \"\",\"unit\": \"kg\"},{\"urn\": \"urn:mdr16:dataelement:30:1\",\"placeholder\": \"\",\"unit\": \"cm\"},{\"urn\": \"urn:mdr16:dataelement:28:1\",\"placeholder\": \"\",\"unit\": \"years\"},{\"urn\": \"urn:mdr16:dataelement:14:1\",\"placeholder\": \"\",\"unit\": \"years\"},{\"urn\": \"urn:mdr16:dataelement:27:1\",\"placeholder\": \"e.g. C25.1\",\"unit\": \"\"}]'
      MDR_HIDDEN:           '[\"urn:mdr16:dataelement:1:1\",\"urn:mdr16:dataelement:25:1\",\"urn:mdr16:dataelement:34:1\",\"urn:mdr16:dataelement:18:1\",\"urn:mdr16:dataelement:11:1\",\"urn:mdr16:dataelement:19:1\",\"urn:mdr16:dataelement:30:1\",\"urn:mdr16:dataelement:4:1\",\"urn:mdr16:dataelement:21:1\",\"urn:mdr16:dataelement:22:1\",\"urn:mdr16:dataelement:24:1\",\"urn:mdr16:dataelement:13:1\"]'
      CATALINA_OPTS:        '"-Xmx1g"'
    networks:
      - gba
    restart: always

  searchbroker:
    image: martinbreu/searchbroker:5.1.1
    environment:
      AUTH_CLIENT_ID:     ${AUTH_CLIENT_ID:-DUMMY}
      POSTGRES_HOST:      "searchbroker-db"
      POSTGRES_DB:        "searchbroker"
      POSTGRES_PORT:      "5432"
      POSTGRES_USER:      "searchbroker"
      POSTGRES_PASS:      "searchbroker"
      MAIL_HOST:          "DUMMY"
      MAIL_FROM_ADDRESS:  "DUMMY"
      MAIL_FROM_NAME:     "DUMMY"
      AUTH_HOST:          "https://login.bbmri-eric.eu"
      AUTH_PUBLIC_KEY:    "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjKvsfThd4XO/J5PDlgnmCZ3vGB8MRwcK4rJ42xO/xVmtwkxV8ZW4LIbRE+uQn4EsyTY8ke9do2sSUHGSIHh6T0OR1nm9eljOEXwO6/kYPJbVvEYRIQaZ5kvuCZEP9dcyHwgaN9thHpo2n71GpVo+kZ/KhUY8XHU7PIUokCPIQrF20CvANa2h8htJMp3mIIBJ2j1sf7qfLo2QAJO5p92zASwPpZSebOFhqU5005Qp7uNB+Rv+1rwL2mclEcXRjmNQmStThOetZLgReoszE3obHyW65UprY269ulKAyqPVm653jtp5aYAt/sP1twgW9UY2+lkOMMpLYwZkTcg3eAW0vQIDAQAB"
      STATISTICS_MAILS:   "${STATISTICS_MAILS}"
      CATALINA_OPTS:      '"-Xmx1g"'
    networks:
    - gba
    - searchbroker-db
    depends_on:
    - searchbroker-db
    restart: always

  searchbroker-db:
    image: postgres:9.6
    environment:
      POSTGRES_USER:      "searchbroker"
      POSTGRES_PASSWORD:  "searchbroker"
      POSTGRES_DB:        "searchbroker"
    networks:
    - searchbroker-db
    expose:
    - 5432
    volumes:
    - searchbroker-db-data:/var/lib/postgresql/data
    restart: always

networks:
  gba:
    driver: bridge
  searchbroker-db:
    driver: bridge

volumes:
  searchbroker-db-data:
